[package]
name = "libindylite"
version = "0.1.0"
authors = ["Spencer Holman <spencer.holman@evernym.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.1"
base64 = {version = "0.6.0", optional = true}
serde = "1.0"
serde_json = "1.0"